name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Docker 이미지 빌드
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/front .

      - name: Docker 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/front

  deploy:
    name: CD
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_ID }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/front
            sudo docker stop front
            sudo docker container rm front
            sudo docker run -dit -p 80:3000 --name front ${{secrets.DOCKERHUB_USERNAME}}/front
            sudo docker image prune -f
